# Generated by Django 4.2.7 on 2025-01-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botusermodel',
            name='first_name',
            field=models.CharField(blank=True, help_text='Enter first name,', max_length=300, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='botusermodel',
            name='last_name',
            field=models.CharField(default='user', help_text='Enter last name', max_length=300, verbose_name='Last Name'),
        ),
    ]
