# Generated by Django 4.2.7 on 2025-01-16 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_botusermodel_first_name_botusermodel_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', help_text='Enter name', max_length=300, verbose_name='Name')),
                ('code', models.CharField(help_text='Auto-generated unique 4-digit numeric code', max_length=4, unique=True, verbose_name='Code')),
                ('users', models.ManyToManyField(to='app.botusermodel')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
            },
        ),
        migrations.CreateModel(
            name='TestParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participated_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the user participated in the test', verbose_name='Participation Date')),
                ('correct_answer', models.CharField(blank=True, help_text='Correct answer', max_length=3000, null=True, verbose_name='Correct Answer')),
                ('wrong_answer', models.CharField(blank=True, help_text='Wrong answer', max_length=3000, null=True, verbose_name='Wrong Answer')),
                ('answers', models.CharField(blank=True, help_text='Answers', max_length=3000, null=True, verbose_name='Answers')),
                ('certificate', models.BooleanField(default=False, verbose_name='Certificate')),
                ('test', models.ForeignKey(help_text='The test being participated in', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='app.test', verbose_name='Test')),
                ('user', models.ForeignKey(help_text='The user participating in the test', on_delete=django.db.models.deletion.CASCADE, related_name='test_participations', to='app.botusermodel', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Test Participation',
                'verbose_name_plural': 'Test Participations',
                'unique_together': {('user', 'test')},
            },
        ),
    ]
