# Generated by Django 4.2.7 on 2025-01-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_test_testparticipation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='users',
        ),
        migrations.AddField(
            model_name='test',
            name='answers',
            field=models.CharField(blank=True, help_text='Enter answers', max_length=3000, null=True, verbose_name='Answers'),
        ),
        migrations.AddField(
            model_name='test',
            name='count',
            field=models.IntegerField(default=0, help_text='Enter count', verbose_name='Count'),
        ),
        migrations.AddField(
            model_name='test',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='type',
            field=models.CharField(default='Test', help_text='Enter type', max_length=3000, verbose_name='Type'),
        ),
    ]
