# Generated by Django 4.2.7 on 2025-01-17 10:26

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_test_users_test_answers_test_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='owner',
            field=models.ForeignKey(default=builtins.print, on_delete=django.db.models.deletion.CASCADE, to='app.botusermodel', verbose_name='Owner'),
            preserve_default=False,
        ),
    ]
