# Generated by Django 4.2.7 on 2025-01-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_test_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Status'),
        ),
    ]
