# Generated by Django 4.2.7 on 2025-02-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_test_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file_ids', models.JSONField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
